version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  bender:
    build: ../..
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    ports:
      - 8090:8090
